# -*- coding: utf-8 -*-
"""
TOUPTI GYM CASA - Apply groups.description fix to the live Supabase DB.

Reads fix_groups_description.sql (generated by generate_sql.py) and PATCHes
the `groups` table via the Supabase REST API so "Créer un Abonnement" →
section 3 "Activités, Groupes & Cours" shows Groupes and Cours.

Usage:
    python data_base_casa/apply_groups_description_fix.py
"""
import json
import os
import re
import sys
import urllib.request

BASE = "https://atvdorphwnpzhobvfmtz.supabase.co"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_PATH = os.path.join(ROOT, "supabase", ".env")
FIX_PATH = os.path.join(ROOT, "data_base_casa", "fix_groups_description.sql")


def load_service_key():
    with open(ENV_PATH, encoding="utf-8") as f:
        for line in f:
            if line.startswith("SUPABASE_SERVICE_ROLE_KEY="):
                key = line.split("=", 1)[1].strip()
                if key:
                    return key
    sys.exit("SUPABASE_SERVICE_ROLE_KEY not found in supabase/.env")


def parse_fix_sql(path):
    with open(path, encoding="utf-8") as f:
        sql = f.read()
    pairs = []
    pattern = re.compile(
        r"UPDATE groups SET description = '((?:[^']|'')*)' WHERE name = '((?:[^']|'')*)';"
    )
    for m in pattern.finditer(sql):
        desc = m.group(1).replace("''", "'")
        name = m.group(2).replace("''", "'")
        pairs.append((name, desc))
    return pairs


def api_request(key, path, method="GET", body=None):
    headers = {
        "apikey": key,
        "Authorization": "Bearer " + key,
        "Content-Type": "application/json",
    }
    data = None
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Prefer"] = "return=representation"
    req = urllib.request.Request(BASE + path, data=data, method=method, headers=headers)
    with urllib.request.urlopen(req) as r:
        raw = r.read().decode("utf-8")
        return json.loads(raw) if raw else None


def main():
    key = load_service_key()
    pairs = parse_fix_sql(FIX_PATH)
    print(f"Parsed {len(pairs)} group descriptions from fix_groups_description.sql")

    groups = api_request(key, "/rest/v1/groups?select=id,name&order=name.asc")
    by_name = {g["name"]: g["id"] for g in groups}
    print(f"Fetched {len(by_name)} groups from DB")

    missing = []
    updated = 0
    for name, desc in pairs:
        gid = by_name.get(name)
        if not gid:
            missing.append(name)
            continue
        api_request(key, "/rest/v1/groups?id=eq." + gid, method="PATCH", body={"description": desc})
        updated += 1
        print(f"  ✓ {name} <- {desc}")

    print(f"\nUpdated {updated}/{len(pairs)} groups")
    if missing:
        print("NOT FOUND in DB (skip):", missing)


if __name__ == "__main__":
    main()