-- ============================================================
-- TOUPTI GYM CASA - DATA IMPORT - FILE 2 OF 8
-- HORAIRES (exercises table - name = groupe, group_id = activité)
-- ============================================================

-- Run this AFTER FILE 1
-- ============================================================

INSERT INTO exercises (name, day, type, start_time, end_time, coach_id, group_id) VALUES
  ('TOUP''TI POUSS/MOUSS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('TOUP''TI POUSS/MOUSS', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Mardi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITS FILOUS', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('MALINS', 'Mardi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('GRANDS MALINS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRENOUILLES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('TÊTARDS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('SUPER TÊTARDS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUSSEF KENZEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('SUPER TÊTARDS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('BALEINES', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CANARDS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('BALEINES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CYCLE DE NATATION', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'SOUFIANE EL HADDAD' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('KOALAS', 'Mardi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS', 'Mercredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES', 'Mercredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS', 'Samedi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES', 'Mardi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES', 'Vendredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES', 'Samedi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS', 'Samedi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('P''TITES CANAILLES', 'Mardi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('LIONS', 'Vendredi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('LIONS', 'Mercredi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('LIONS', 'Mercredi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('LIONS', 'Samedi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('KANGOUROUS', 'Vendredi', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('GUÊPARDS', 'Mercredi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('GUÊPARDS', 'Samedi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('P''TITS FILOUS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('KANGOUROUS', 'Samedi', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('BALEINES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GUÊPARDS', 'Vendredi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('GRENOUILLES', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRANDS MALINS', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('BALEINES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('REQUINS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Mardi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('BALEINES', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('REQUINS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Samedi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('P''TITES CANAILLES', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('BALEINES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('TÊTARDS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS SENIOR', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('P''TITES CANAILLES', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Mardi', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('GRANDS MALINS', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('KANGOUROUS', 'Mercredi', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('KANGOUROUS', 'Samedi', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('GRENOUILLES', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('MALINS', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('COCCINELLES', 'Mardi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('TAUREAUX', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('GRANDS MALINS', 'Mardi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('DRAGONS', 'Vendredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('P''TITES CANAILLES', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('CORADIONS SENIOR', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'SOUFIANE EL HADDAD' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRANDS MALINS', 'Mardi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Mardi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES CANAILLES', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Mardi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('OURS', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('GRENOUILLES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('TIGRES', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TAUREAUX', 'Mardi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('OURS', 'Mercredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('KOALAS', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('OURS', 'Samedi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('TAUREAUX', 'Mercredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('TAUREAUX', 'Samedi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('GRENOUILLES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS SENIOR', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('STAFF', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('TIGRES', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('LIONS', 'Jeudi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('GUÊPARDS', 'Jeudi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('COCCINELLES', 'Mercredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('COCCINELLES', 'Mercredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('PAPILLONS', 'Mercredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('DRAGONS', 'Mercredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('COCCINELLES', 'Vendredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('PAPILLONS', 'Vendredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('CANARDS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRANDS MALINS', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('REQUINS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CYCLE DE NATATION', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS SENIOR', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CYCLE DE NATATION', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CANARDS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('KANGOUROUS', 'Jeudi', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('KOALAS', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TAUREAUX', 'Dimanche', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('GRANDS MALINS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('TOUP''TI POUSS/MOUSS', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('MALINS', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('OURS', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('KOALAS', 'Vendredi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS', 'Mardi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('OURS', 'Mardi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('TAUREAUX', 'Mardi', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('TIGRES', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('CYCLE DE NATATION', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('REQUINS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Samedi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('PAPILLONS', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('PISCINE 1', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('7 - 14 ANS', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'SELF-DEFENSE' LIMIT 1)),
  ('7 - 14 ANS', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'SELF-DEFENSE' LIMIT 1)),
  ('7 - 14 ANS', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'SELF-DEFENSE' LIMIT 1)),
  ('TÊTARDS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('LIONS', 'Mardi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('GUÊPARDS', 'Mardi', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('DAUPHINS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('KOALAS', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('GUÊPARDS', 'Mercredi', 'Football', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('KANGOUROUS', 'Mardi', 'Basketball', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('KOALAS', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('3-6 ANS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('7-14 ANS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('3-6 ANS', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('7-14 ANS', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('3-6 ANS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('7-14 ANS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('3-6 ANS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('7-14 ANS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('3-6 ANS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Mardi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1));

-- ============================================================
-- FILE 2 DONE! ✅
-- ============================================================
