-- ============================================================
-- TOUPTI GYM CASA - DATA IMPORT - FILE 1 OF 8
-- SETUP + REFERENCE DATA (Activities, Groups, Trainers, Schedules)
-- ============================================================

-- Run this FIRST in the Supabase SQL Editor
-- https://supabase.com/dashboard/project/atvdorphwnpzhobvfmtz/sql/new
-- ============================================================

INSERT INTO exercises (name, day, type, start_time, end_time) VALUES
  ('NATATION', 'Monday', 'Swimming', '09:00:00', '10:00:00'),
  ('GYMNASTIQUE 1', 'Monday', 'Gymnastics', '09:00:00', '10:00:00'),
  ('FOOTBALL', 'Monday', 'Football', '09:00:00', '10:00:00'),
  ('BASKETBALL', 'Monday', 'Basketball', '09:00:00', '10:00:00'),
  ('ARTS MARTIAUX', 'Monday', 'Other', '09:00:00', '10:00:00'),
  ('GYMNASTIQUE 2', 'Monday', 'Gymnastics', '09:00:00', '10:00:00'),
  ('KICK-BOXING', 'Monday', 'Other', '09:00:00', '10:00:00'),
  ('NATATION 2', 'Monday', 'Swimming', '09:00:00', '10:00:00'),
  ('DANSE CLASSIQUE', 'Monday', 'Other', '09:00:00', '10:00:00'),
  ('KUNG FU', 'Monday', 'Other', '09:00:00', '10:00:00'),
  ('SPORTS BALLONS', 'Monday', 'Other', '09:00:00', '10:00:00'),
  ('STAFF', 'Monday', 'Other', '09:00:00', '10:00:00'),
  ('BABY SPA', 'Monday', 'Other', '09:00:00', '10:00:00'),
  ('ABSENCES', 'Monday', 'Other', '09:00:00', '10:00:00'),
  ('SELF-DEFENSE', 'Monday', 'Other', '09:00:00', '10:00:00'),
  ('STAGE DE NATATION P1', 'Monday', 'Swimming', '09:00:00', '10:00:00'),
  ('STAGE NATATION P2', 'Monday', 'Swimming', '09:00:00', '10:00:00');

INSERT INTO groups (name) VALUES
  ('TOUP''TI POUSS/MOUSS'),
  ('P''TITES FRIPOUILLES'),
  ('VOLTIGEURS DÉBUTANT'),
  ('P''TITS FILOUS'),
  ('MALINS'),
  ('GRANDS MALINS'),
  ('GRENOUILLES'),
  ('TÊTARDS'),
  ('SUPER TÊTARDS'),
  ('CANARDS'),
  ('BALEINES'),
  ('CYCLE DE NATATION'),
  ('KOALAS'),
  ('TIGRES'),
  ('DRAGONS'),
  ('P''TITES CANAILLES'),
  ('LIONS'),
  ('KANGOUROUS'),
  ('GUÊPARDS'),
  ('DAUPHINS'),
  ('CORADIONS SENIOR'),
  ('REQUINS'),
  ('CORADIONS JUNIOR'),
  ('COCCINELLES'),
  ('TAUREAUX'),
  ('OURS'),
  ('STAFF'),
  ('PAPILLONS'),
  ('RDV INDIVIDUEL'),
  ('RDV EN BINÔME'),
  ('PISCINE 1'),
  ('PISCINE 2'),
  ('7 - 14 ANS'),
  ('3-6 ANS'),
  ('7-14 ANS');

INSERT INTO trainers (name) VALUES
  ('ABDELMALEK CHAKIR'),
  ('ANAS BOULGANA'),
  ('YOUSSEF KENZEDDINE'),
  ('SOUFIANE EL HADDAD'),
  ('ABDELHAMID SAADEDDINE'),
  ('KAMAL SLAOUI'),
  ('YOUNES EL HASSANI'),
  ('AZIZ TOUMI'),
  ('IRYNA MUZYKA'),
  ('RIDA MOURAK');

INSERT INTO exercises (name, day, type, start_time, end_time, coach_id, group_id) VALUES
  ('GYMNASTIQUE 1', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'TOUP''TI POUSS/MOUSS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'TOUP''TI POUSS/MOUSS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Thursday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'TÊTARDS' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUSSEF KENZEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'SUPER TÊTARDS' LIMIT 1)),
  ('NATATION', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'SUPER TÊTARDS' LIMIT 1)),
  ('NATATION', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION 2', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION 2', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CYCLE DE NATATION' LIMIT 1)),
  ('NATATION', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'SOUFIANE EL HADDAD' LIMIT 1), (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'KOALAS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'KOALAS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'TIGRES' LIMIT 1)),
  ('ARTS MARTIAUX', 'Saturday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'KOALAS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'TIGRES' LIMIT 1)),
  ('ARTS MARTIAUX', 'Friday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'TIGRES' LIMIT 1)),
  ('ARTS MARTIAUX', 'Saturday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'TIGRES' LIMIT 1)),
  ('ARTS MARTIAUX', 'Saturday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'DRAGONS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('FOOTBALL', 'Friday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'LIONS' LIMIT 1)),
  ('FOOTBALL', 'Wednesday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'LIONS' LIMIT 1)),
  ('FOOTBALL', 'Wednesday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'LIONS' LIMIT 1)),
  ('FOOTBALL', 'Saturday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'LIONS' LIMIT 1)),
  ('BASKETBALL', 'Friday', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'KANGOUROUS' LIMIT 1)),
  ('FOOTBALL', 'Wednesday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'GUÊPARDS' LIMIT 1)),
  ('FOOTBALL', 'Saturday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'GUÊPARDS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('BASKETBALL', 'Saturday', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'KANGOUROUS' LIMIT 1)),
  ('NATATION 2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('FOOTBALL', 'Friday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'GUÊPARDS' LIMIT 1)),
  ('NATATION', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('NATATION 2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DAUPHINS' LIMIT 1)),
  ('NATATION 2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DAUPHINS' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DAUPHINS' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'REQUINS' LIMIT 1)),
  ('NATATION 2', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DAUPHINS' LIMIT 1)),
  ('NATATION 2', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('NATATION', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION 2', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DAUPHINS' LIMIT 1)),
  ('NATATION 2', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DAUPHINS' LIMIT 1)),
  ('NATATION 2', 'Friday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('NATATION 2', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('NATATION 2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'REQUINS' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'CORADIONS JUNIOR' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('NATATION 2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'TÊTARDS' LIMIT 1)),
  ('NATATION 2', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('NATATION 2', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('BASKETBALL', 'Wednesday', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'KANGOUROUS' LIMIT 1)),
  ('BASKETBALL', 'Saturday', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'KANGOUROUS' LIMIT 1)),
  ('NATATION', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION 2', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS JUNIOR' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('DANSE CLASSIQUE', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'COCCINELLES' LIMIT 1)),
  ('KICK-BOXING', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'TAUREAUX' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Friday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'DRAGONS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('NATATION 2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('NATATION 2', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('NATATION', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'SOUFIANE EL HADDAD' LIMIT 1), (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION 2', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS JUNIOR' LIMIT 1)),
  ('NATATION 2', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS JUNIOR' LIMIT 1)),
  ('NATATION 2', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('NATATION 2', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('NATATION 2', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS JUNIOR' LIMIT 1)),
  ('NATATION 2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BALEINES' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('KICK-BOXING', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'OURS' LIMIT 1)),
  ('NATATION', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('ARTS MARTIAUX', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'TIGRES' LIMIT 1)),
  ('KICK-BOXING', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'TAUREAUX' LIMIT 1)),
  ('KICK-BOXING', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'OURS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KOALAS' LIMIT 1)),
  ('KICK-BOXING', 'Saturday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'OURS' LIMIT 1)),
  ('KICK-BOXING', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'TAUREAUX' LIMIT 1)),
  ('KICK-BOXING', 'Saturday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'TAUREAUX' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS JUNIOR' LIMIT 1)),
  ('STAFF', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('NATATION 2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS JUNIOR' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS JUNIOR' LIMIT 1)),
  ('NATATION', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('NATATION 2', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS JUNIOR' LIMIT 1)),
  ('ARTS MARTIAUX', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'TIGRES' LIMIT 1)),
  ('ARTS MARTIAUX', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DRAGONS' LIMIT 1)),
  ('FOOTBALL', 'Thursday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'LIONS' LIMIT 1)),
  ('FOOTBALL', 'Thursday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'GUÊPARDS' LIMIT 1)),
  ('DANSE CLASSIQUE', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'COCCINELLES' LIMIT 1)),
  ('DANSE CLASSIQUE', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'COCCINELLES' LIMIT 1)),
  ('DANSE CLASSIQUE', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'PAPILLONS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'DRAGONS' LIMIT 1)),
  ('BABY SPA', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV INDIVIDUEL' LIMIT 1)),
  ('BABY SPA', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('BABY SPA', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'RDV EN BINÔME' LIMIT 1)),
  ('DANSE CLASSIQUE', 'Friday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'COCCINELLES' LIMIT 1)),
  ('DANSE CLASSIQUE', 'Friday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'PAPILLONS' LIMIT 1)),
  ('NATATION', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRENOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('NATATION 2', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'REQUINS' LIMIT 1)),
  ('NATATION', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CYCLE DE NATATION' LIMIT 1)),
  ('NATATION 2', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('NATATION 2', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CYCLE DE NATATION' LIMIT 1)),
  ('NATATION', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('BASKETBALL', 'Thursday', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'KANGOUROUS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KOALAS' LIMIT 1)),
  ('KICK-BOXING', 'Sunday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'TAUREAUX' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GRANDS MALINS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'TOUP''TI POUSS/MOUSS' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITS FILOUS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'MALINS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES FRIPOUILLES' LIMIT 1)),
  ('GYMNASTIQUE 1', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'P''TITES CANAILLES' LIMIT 1)),
  ('KICK-BOXING', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'OURS' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('GYMNASTIQUE 2', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'VOLTIGEURS DÉBUTANT' LIMIT 1)),
  ('ARTS MARTIAUX', 'Friday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'KOALAS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'DRAGONS' LIMIT 1)),
  ('KICK-BOXING', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'OURS' LIMIT 1)),
  ('KICK-BOXING', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'TAUREAUX' LIMIT 1)),
  ('ARTS MARTIAUX', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'TIGRES' LIMIT 1)),
  ('ARTS MARTIAUX', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DRAGONS' LIMIT 1)),
  ('NATATION', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CYCLE DE NATATION' LIMIT 1)),
  ('NATATION 2', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'REQUINS' LIMIT 1)),
  ('NATATION 2', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DAUPHINS' LIMIT 1)),
  ('NATATION 2', 'Sunday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'CORADIONS JUNIOR' LIMIT 1)),
  ('NATATION 2', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'CORADIONS SENIOR' LIMIT 1)),
  ('DANSE CLASSIQUE', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PAPILLONS' LIMIT 1)),
  ('ABSENCES', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 1' LIMIT 1)),
  ('ABSENCES', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 2' LIMIT 1)),
  ('ABSENCES', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 1' LIMIT 1)),
  ('ABSENCES', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 2' LIMIT 1)),
  ('ABSENCES', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 1' LIMIT 1)),
  ('ABSENCES', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 2' LIMIT 1)),
  ('ABSENCES', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 1' LIMIT 1)),
  ('ABSENCES', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 2' LIMIT 1)),
  ('ABSENCES', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 1' LIMIT 1)),
  ('ABSENCES', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 2' LIMIT 1)),
  ('ABSENCES', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 1' LIMIT 1)),
  ('ABSENCES', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 2' LIMIT 1)),
  ('ABSENCES', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 1' LIMIT 1)),
  ('ABSENCES', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'PISCINE 2' LIMIT 1)),
  ('SELF-DEFENSE', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7 - 14 ANS' LIMIT 1)),
  ('SELF-DEFENSE', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7 - 14 ANS' LIMIT 1)),
  ('SELF-DEFENSE', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7 - 14 ANS' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'TÊTARDS' LIMIT 1)),
  ('NATATION', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'CANARDS' LIMIT 1)),
  ('FOOTBALL', 'Tuesday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'LIONS' LIMIT 1)),
  ('FOOTBALL', 'Tuesday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'GUÊPARDS' LIMIT 1)),
  ('NATATION 2', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DAUPHINS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KOALAS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DRAGONS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KOALAS' LIMIT 1)),
  ('FOOTBALL', 'Wednesday', 'Football', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GUÊPARDS' LIMIT 1)),
  ('BASKETBALL', 'Tuesday', 'Basketball', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KANGOUROUS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KOALAS' LIMIT 1)),
  ('ARTS MARTIAUX', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'TIGRES' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE NATATION P2', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7-14 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE NATATION P2', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7-14 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE NATATION P2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7-14 ANS' LIMIT 1)),
  ('STAGE NATATION P2', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7-14 ANS' LIMIT 1)),
  ('STAGE NATATION P2', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7-14 ANS' LIMIT 1)),
  ('STAGE NATATION P2', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7-14 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE NATATION P2', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7-14 ANS' LIMIT 1)),
  ('STAGE NATATION P2', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7-14 ANS' LIMIT 1)),
  ('STAGE NATATION P2', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7-14 ANS' LIMIT 1)),
  ('STAGE NATATION P2', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '7-14 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1)),
  ('STAGE DE NATATION P1', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = '3-6 ANS' LIMIT 1));

-- ============================================================
-- FILE 1 DONE! ✅ Run FILE 2 next.
-- ============================================================
