-- ============================================================
-- TOUPTI GYM CASA - DATA IMPORT - FILE 5 OF 8
-- CHILDREN - batch 3/3 (rows 5801-5998)
-- ============================================================

-- Run this AFTER the previous file
-- ============================================================

INSERT INTO children (name, gender, birth_date, age, school, school_type, address, postal_code, client_type, zkteco_id) VALUES
('YAFI IYAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '7 rue tinmes polo - CASABLANCA', NULL, 'Normal', NULL),
('YAFI MOHAMED JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rue rome walili C  CASABLANCA', NULL, 'Normal', NULL),
('YAHYA FATIMA EZZAHRAE', 'Garçon', '2000-01-01', 0, NULL, NULL, '49 rue nahas enahout maarif  CASABLANCA', NULL, 'Normal', NULL),
('YAHYA OTHMANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '49 rue nahas enahoui maarif  CASABLANCA', NULL, 'Normal', NULL),
('YAMIL LOUJAYNE', 'Garçon', '2000-01-01', 0, NULL, NULL, '306 bd abdelmoumen  CASABLANCA', NULL, 'Normal', NULL),
('YAMILE MOHAMED GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'HAY MOULAY ABDELLAH - CASABLANCA', NULL, 'Normal', NULL),
('YANG ZILUO', 'Garçon', '2000-01-01', 0, NULL, NULL, '- 20000 CASABLANCA', NULL, 'Normal', NULL),
('YAROUB ADAM', 'Garçon', '2000-01-01', 0, NULL, NULL, '37, lotissement Bachkou, immeuble Fatine 2, porte 3, étage 1 20420 CASABLANCA', NULL, 'Normal', NULL),
('YAROUB RAYANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '37 LOT BACHKOU IMM FATINE 2 ETG 1 PORTE 3  20420 CASABLANCA', NULL, 'Normal', NULL),
('YASSINE NADA', 'Garçon', '2000-01-01', 0, NULL, NULL, '12 rue talal ben ahmed res karam appt 10 belvedere  20300 CASABLANCA', NULL, 'Normal', NULL),
('YASSINE ZIAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '12 rue rahal ben ahmed res karam appt 16 200000 CASABLANCA', NULL, 'Normal', NULL),
('YASSIR AHMED', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('YASSIR YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res les champs belvedere - CASABLANCA', NULL, 'Normal', NULL),
('YATIM MOHAMMED EL HADI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Résidence Nadia, immeuble 2, appartement 2  CASABLANCA', NULL, 'Normal', NULL),
('YAZAMI GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '22, Lotissement Siham - Quartier les  CASABLANCA', NULL, 'Normal', NULL),
('YAZICI DENIZ', 'Garçon', '2000-01-01', 0, NULL, NULL, '40 rur de roue 2 mars casablanca 20300 CASABLANCA', NULL, 'Normal', NULL),
('YAZIDI KENZA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Lotissement marmar rue 38 californie ain chok   CASABLANCA', NULL, 'Normal', NULL),
('YE QINQIN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('YEDEAN  NOUR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'JENNAN CALIFORNIA 20000 CASABLANCA', NULL, 'Normal', NULL),
('YOUCEF KHODJA ELIAS', 'Garçon', '2000-01-01', 0, NULL, NULL, '70 rue abou marouna abdelmalek res oumayma  CASABLANCA', NULL, 'Normal', NULL),
('YOUCEF KHODJA MALIK', 'Garçon', '2000-01-01', 0, NULL, NULL, '70 rue abou mrouane abdelmalek res oumayma  CASABLANCA', NULL, 'Normal', NULL),
('YOUSSEF MESSAF', 'Garçon', '2000-01-01', 0, NULL, NULL, '', NULL, 'Normal', NULL),
('YOUSSFY FATIMA-ZAHRA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Mandarona ain chok - CASABLANCA', NULL, 'Normal', NULL),
('YOUSSFY YOUSSEF', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Mandarona ainchock - CASABLANCA', NULL, 'Normal', NULL),
('YOUSSOUFI NAEL', 'Garçon', '2000-01-01', 0, NULL, NULL, '153 ANGLE RUE ABOU KACEM ZAHRAOUI 2 BD DRISS 1ER N 7  CASABLANCA', NULL, 'Normal', NULL),
('YOUSSRI JUMANA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Californien05e1 20200 CASABLANCA', NULL, 'Normal', NULL),
('YUAN BAIHAN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bouskoura - BOUSKOURA', NULL, 'Normal', NULL),
('YUAN MIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'LOT PANORAMIQUE  - CASABLANCA', NULL, 'Normal', NULL),
('YURUK RANA-JIRAN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Roche noir hay hassania imm 62 n 5 20570 CASABLANCA', NULL, 'Normal', NULL),
('ZAABLI LINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZAABOUL AYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '32-02 res du jardin, casa green town   CASABLANCA', NULL, 'Normal', NULL),
('ZAAM EL YAZID', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RUE CONSTENTINIBLE N 1 EL MECHOUAR  CASABLANCA', NULL, 'Normal', NULL),
('ZAAM JIHANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RUE CONTANTINOBLE N 1. EL MECHOUAR  CASABLANCA', NULL, 'Normal', NULL),
('ZAARAOUI IBRAHIM', 'Garçon', '2000-01-01', 0, NULL, NULL, '14 RUE DU RROUISSILLON RES PALACE 2 MARS QUT DES HOP  CASABLANCA', NULL, 'Normal', NULL),
('ZAARI AMIR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA - CASABLANCA', NULL, 'Normal', NULL),
('ZAAZAA ABDERRAHMANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RESIDENCE LOT ALLAH N 39 HAY ADIL HAY MOHAMMADI  CASABLANCA', NULL, 'Normal', NULL),
('ZABOUJ ELI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rés LES CRETES - CASABLANCA', NULL, 'Normal', NULL),
('ZACCARIA LEYLA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZACCARIA SOPHIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZADAKI AYLAL', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bvd abderrahim  bouabid.res oasis  harmany .etage 2n6 ----- CASABLANCA', NULL, 'Normal', NULL),
('ZADAKI ILIAN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Boulevard de la mecque, résidence Porte Californie, al wiam, appt 16  CASABLANCA', NULL, 'Normal', NULL),
('ZADAKI LILIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Boulevard de la Mecque, résidence Porte Californie, al wiam, appt 16  CASABLANCA', NULL, 'Normal', NULL),
('ZAFAR SAAD', 'Garçon', '2000-01-01', 0, NULL, NULL, 'AL ANDALOUS - CASABLANCA', NULL, 'Normal', NULL),
('ZAFFOU  ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Lot abderrahman rue 6 n 2 app n 4 californe 20150 CASABLANCA', NULL, 'Normal', NULL),
('ZAFFOU BASSMA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Lot abderrahman rue 6 n2 app 4 californie 20150 CASABLANCA', NULL, 'Normal', NULL),
('ZAFFOU MALAK', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Lot abderrahman rue 6 n2 app n4 califorie 20150 CASABLANCA', NULL, 'Normal', NULL),
('ZAGHIR ISMAIL', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Belvedere - CASABLANCA', NULL, 'Normal', NULL),
('ZAGHLOUL HAJAR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RUE MOUDIBOUTIKAT 20000- CASABLANCA', NULL, 'Normal', NULL),
('ZAHDANI JOUD', 'Garçon', '2000-01-01', 0, NULL, NULL, '6 rue des Mésauges Oasis - CASABLANCA', NULL, 'Normal', NULL),
('ZAHDI AMIR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'VILLA HADDIOUI BD ABOUBAKR EL KADIRI BOUSKOURA   BOUSKOURA', NULL, 'Normal', NULL),
('ZAHDI HAMZA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'VILLA HADDIOUI BD ABOUBAKR EL KADIRI BOUSKOURA   BOUSKOURA', NULL, 'Normal', NULL),
('ZAHDI KHADIJA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'VILLA HADDIOUI BD ABOUBAKR EL KADIRI BOUSKOURA', NULL, 'Normal', NULL),
('ZAHER YAHYA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Lot floride n:15 sidi maarouf   CASABLANCA', NULL, 'Normal', NULL),
('ZAHI MOHAMED', 'Garçon', '2000-01-01', 0, NULL, NULL, '17 app 4eme etage residence el manar II oualfa - CASABLANCA', NULL, 'Normal', NULL),
('ZAHI NOHA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Appt 17 residence el manar II oualfa - CASABLANCA', NULL, 'Normal', NULL),
('ZAHIR AHMED', 'Garçon', '2000-01-01', 0, NULL, NULL, '14rueharitel mouhassib ------ CASABLANCA', NULL, 'Normal', NULL),
('ZAHIR AYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '5, rue Saint savin, appartement 21  CASABLANCA', NULL, 'Normal', NULL),
('ZAHIR HIBA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'ROUTE DE BOUSKOURA HYDE PARCK VILLA 4 20300 CASABLANCA', NULL, 'Normal', NULL),
('ZAHIR SABRINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '5, rue Saint Sovain  CASABLANCA', NULL, 'Normal', NULL),
('ZAHLANE GHITA', 'Garçon', '2000-01-01', 0, NULL, NULL, '119, boulevard Bourgogne  CASABLANCA', NULL, 'Normal', NULL),
('ZAHLANE JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZAHNI ISMAIL', 'Garçon', '2000-01-01', 0, NULL, NULL, '9 RUE DE  NAUSOLEE RESIDENCE LINA 2 APPARTEMENT 4 QUARTIER DES HOPITAUX  CASABLANCA', NULL, 'Normal', NULL),
('ZAHNI KARIM', 'Garçon', '2000-01-01', 0, NULL, NULL, '9 RUE DU NAUSDEE RESIDENCE LINA 2 APPARTEMENT 4 QUARTIER DES HOPITAUX  CASABLANCA', NULL, 'Normal', NULL),
('ZAHOUILY ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '90 angle rue tarik bnou ziad et 2 mars  CASABLANCA', NULL, 'Normal', NULL),
('ZAHOUILY MOUAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '90 angle rue tarik bnou ziyad et 2 mars appt 05  CASABLANCA', NULL, 'Normal', NULL),
('ZAHRANI MOHAMED', 'Garçon', '2000-01-01', 0, NULL, NULL, '55, RUE ABOU ALAAZAHR, RES DU PALAIS APPT 7 20360 CASABLANCA', NULL, 'Normal', NULL),
('ZAHRAOUI MED ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res younes appt 4 hay wiam
  CASABLANCA', NULL, 'Normal', NULL),
('ZAHRAOUI RIM', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res younes appt 4 hay wiam
  CASABLANCA', NULL, 'Normal', NULL),
('ZAHRI HAROUN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Brchidie de californie - CASABLANCA', NULL, 'Normal', NULL),
('ZAID SARA', 'Garçon', '2000-01-01', 0, NULL, NULL, '12, rue mabillon, appt 6; Val Fleuri - MAARIF  CASABLANCA', NULL, 'Normal', NULL),
('ZAIM WADGHIRI YOUSSEF', 'Garçon', '2000-01-01', 0, NULL, NULL, '45 bd omar khiam casa - CASABLANCA', NULL, 'Normal', NULL),
('ZAIT JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZAKARANI ADNANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZAKARANI SOFIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Aéroport Benslimane, Villa Phoenix B5  CASABLANCA', NULL, 'Normal', NULL),
('ZAKARI ILYAS', 'Garçon', '2000-01-01', 0, NULL, NULL, '39 El Arbi Doghmi; Fz Villa II 21100 CASABLANCA', NULL, 'Normal', NULL),
('ZAKARYA YAHYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '5, avenue des pleiades, résidence Imane, 3ème étage, appt 9-TONTONVILLE  CASABLANCA', NULL, 'Normal', NULL),
('ZAKHROUF YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZAKI GHITA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BD GHANDI - OASIS - CASABLANCA', NULL, 'Normal', NULL),
('ZAKI LILYA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res les collines imm j appt 10 sidi maarouf  2000 CASABLANCA', NULL, 'Normal', NULL),
('ZAKI OTHMANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Résidence Perla 7, n°47, 4ème étage, n°47 - MAARIF EXTENSION  CASABLANCA', NULL, 'Normal', NULL),
('ZAKIR NIHAL', 'Garçon', '2000-01-01', 0, NULL, NULL, '86 BD  POLO 20000 CASABLANCA', NULL, 'Normal', NULL),
('ZAKOUARI  JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rés dianne 4etg N 17 taddart  2000 CASABLANCA', NULL, 'Normal', NULL),
('ZAMRANE YOUNES', 'Garçon', '2000-01-01', 0, NULL, NULL, '18 RUE AMSTERDAM. RES SARA B N 7 QUARTIER 2 MARS   CASABLANCA', NULL, 'Normal', NULL),
('ZAOUAK MOHAMED KINAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '02 RUE GREEN HOUSE  CASABLANCA', NULL, 'Normal', NULL),
('ZAOURI HALA', 'Garçon', '2000-01-01', 0, NULL, NULL, '7, rue mausolée, n°9  CASABLANCA', NULL, 'Normal', NULL),
('ZARAK MALAK', 'Garçon', '2000-01-01', 0, NULL, NULL, '17 BIS RUE DES PALMIERS . OASIS CASA   CASABLANCA', NULL, 'Normal', NULL),
('ZARHOUNI LINA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BOUSKOURA - BOUSKOURA', NULL, 'Normal', NULL),
('ZARHOUNI MERYAM', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rue raqib med missaoui apt 243 imb ain borja 20320 CASABLANCA', NULL, 'Normal', NULL),
('ZARHOUNI MOHAMED GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'A  CASABLANCA', NULL, 'Normal', NULL),
('ZARHOUNI YANIS', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BOUSKOURA - BOUSKOURA', NULL, 'Normal', NULL),
('ZARHOUNI YOUSRA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Z  CASABLANCA', NULL, 'Normal', NULL),
('ZARHOUNI YOUSSEF', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rue raqib med missaoui , APT 243 IMB AIN BORJA 20320 CASABLANCA', NULL, 'Normal', NULL),
('ZARKAOUI YOUSRA', 'Garçon', '2000-01-01', 0, NULL, NULL, '18 rue anoual, mustapha el maani  CASABLANCA', NULL, 'Normal', NULL),
('ZAROUALI ALAOUI  OMAR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA --- CASABLANCA', NULL, 'Normal', NULL),
('ZAROUALI HIBATALLAH', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Hay omar ibno lkhatab rue 15 imm A n 137  CASABLANCA', NULL, 'Normal', NULL),
('ZAYOU YAKOUT', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CALIFORNIE   CASABLANCA', NULL, 'Normal', NULL),
('ZAYYOUN NAEL', 'Garçon', '2000-01-01', 0, NULL, NULL, 'APPT 3/ IMM 8. RES LES JARDINS AL MIRAJ. LISSASFA1.   CASABLANCA', NULL, 'Normal', NULL),
('ZAZOU JENNA', 'Garçon', '2000-01-01', 0, NULL, NULL, '1 rue maidani res palmier  20304 CASABLANCA', NULL, 'Normal', NULL),
('ZBIR YAKOUT', 'Garçon', '2000-01-01', 0, NULL, NULL, '165 BD ABDELMOUMEN RES LES CHAMPS CENTER  CASABLANCA', NULL, 'Normal', NULL),
('ZEJLI ILYAN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CALIFORNIE PARC, BAT 3 ETAGE 2 N°6 90150 CASABLANCA', NULL, 'Normal', NULL),
('ZEKKANI MED TAHA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Benjdia   CASABLANCA', NULL, 'Normal', NULL),
('ZEKRI OTHMANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BOUSKOURA VILLA 13', NULL, 'Normal', NULL),
('ZEMMARI NADA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZEMMARI OMAR', 'Garçon', '2000-01-01', 0, NULL, NULL, '429 bd abdelmoumenresidence ryad abdelmoumen imm d appt 6 2eme etage   CASABLANCA', NULL, 'Normal', NULL),
('ZEMMOURI YASSMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RES THE PARK ANFA BD DES CLUBS IMM A6 APP 13 - CASABLANCA', NULL, 'Normal', NULL),
('ZENDOUZI  SELMA', 'Garçon', '2000-01-01', 0, NULL, NULL, '12 res bay view ain diab anfa sup   CASABLANCA', NULL, 'Normal', NULL),
('ZENDOUZI RANIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Residence porte californie', NULL, 'Normal', NULL),
('ZERGUIT LINA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'LOT EL KHZIR RUE 71 N°11 AIN CHOCK 20000 CASABLANCA', NULL, 'Normal', NULL),
('ZERHOUNI SOFIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Residence les champs3, imm G Apprt 18 Nassim   CASABLANCA', NULL, 'Normal', NULL),
('ZERIOUL JONAS', 'Garçon', '2000-01-01', 0, NULL, NULL, '31.rue badia palmier casablanca  CASABLANCA', NULL, 'Normal', NULL),
('ZERIOUL NOAM', 'Garçon', '2000-01-01', 0, NULL, NULL, '31rue rodin casablaca -- CASABLANCA', NULL, 'Normal', NULL),
('ZERKAOUI ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZEROUAL NAEL', 'Garçon', '2000-01-01', 0, NULL, NULL, 'LES COLINES SIDI MAAROUF 20000 CASABLANCA', NULL, 'Normal', NULL),
('ZEROUALI BOUKHAL YOUSSEF', 'Garçon', '2000-01-01', 0, NULL, NULL, '44 avenue des pleiades   CASABLANCA', NULL, 'Normal', NULL),
('ZEROUALI ELYAN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Boulevard de la mecque, porte californie  20400 CASABLANCA', NULL, 'Normal', NULL),
('ZEROUALI GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RIAD ANDALOUSS KORTOBA CALIFORNIE  CASABLANCA', NULL, 'Normal', NULL),
('ZEROUALI YASSINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '', NULL, 'Normal', NULL),
('ZEROUALI ZYAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '16 rue ibn khairane etg 5 apt 9  CASABLANCA', NULL, 'Normal', NULL),
('ZERRAD  ISMAIL', 'Garçon', '2000-01-01', 0, NULL, NULL, 'N27rue le titien.res premier rase .aprt 24 étage 5val fleurie 20390 CASABLANCA', NULL, 'Normal', NULL),
('ZERRAD ALYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '----- ----- CASABLANCA', NULL, 'Normal', NULL),
('ZERRAD LYNN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BOUSKOURA VILLE VERTE RCE MALMERAIS N° C 24 20000 CASABLANCA', NULL, 'Normal', NULL),
('ZERRARI ISMAEL', 'Garçon', '2000-01-01', 0, NULL, NULL, '12 RUE POINT DU JOUR RACINE  - CASABLANCA', NULL, 'Normal', NULL),
('ZERROUK ADAM', 'Garçon', '2000-01-01', 0, NULL, NULL, '23, angle rue François ponsard et stéphane - VAL FLEURI   CASABLANCA', NULL, 'Normal', NULL),
('ZERROUK RAYAN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bd med5 imm C app52  CASABLANCA', NULL, 'Normal', NULL),
('ZERROUK SAMI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res nesma ibn noussir ghautier 20000 CASABLANCA', NULL, 'Normal', NULL),
('ZERTA RYM', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Lot viremont n 54 56 californie - CASABLANCA', NULL, 'Normal', NULL),
('ZERYOUH AHMED', 'Garçon', '2000-01-01', 0, NULL, NULL, '15 bd zerrktouni casa  CASABLANCA', NULL, 'Normal', NULL),
('ZERYOUH AMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '15bd zerktouni casa   CASABLANCA', NULL, 'Normal', NULL),
('ZHANG  HUI LIN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bd abdlkrim el khatabi  2000 CASABLANCA', NULL, 'Normal', NULL),
('ZHANG  HUIT ZHZN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bd abdelkarim el khatabi  2000 CASABLANCA', NULL, 'Normal', NULL),
('ZHANG  ZE YU', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bd abdlkrim el khatabi  2000 CASABLANCA', NULL, 'Normal', NULL),
('ZHAR LINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '384 villas nasim1  CASABLANCA', NULL, 'Normal', NULL),
('ZHAR MEHDI', 'Garçon', '2000-01-01', 0, NULL, NULL, '384, villa nassim 1 casablanca  CASABLANCA', NULL, 'Normal', NULL),
('ZHDONOV ANASTASIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'PORTE CALIFORNIA 2 APPT 20 - CASABLANCA', NULL, 'Normal', NULL),
('ZHNG SHIWEN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'OUASIS RES MARJANA - CASABLANCA', NULL, 'Normal', NULL),
('ZIATI LAYANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZIDANE  MOHAMED YAZANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'ESSALAMA 01 FLORIDA SIDI MAAROUF  20000 CASABLANCA', NULL, 'Normal', NULL),
('ZIDANE EL GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZIDATE ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '31 LOT ISMAILIA RES PANORAMIQUE. CALIFORNIE   CASABLANCA', NULL, 'Normal', NULL),
('ZIDATE JANA', 'Garçon', '2000-01-01', 0, NULL, NULL, '31 lot ismailia residence panoramique californie  CASABLANCA', NULL, 'Normal', NULL),
('ZIDI ADAM', 'Garçon', '2000-01-01', 0, NULL, NULL, '1, allée chant d''oiseaux - L''HERMITAGE  CASABLANCA', NULL, 'Normal', NULL),
('ZIDI ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '115 residence canstautinoise bd resistance  20030 CASABLANCA', NULL, 'Normal', NULL),
('ZIDI DINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '1-, allée Chant d''oiseaux - HERMITAGE  CASABLANCA', NULL, 'Normal', NULL),
('ZILI AMIRA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZINE  ADAM', 'Garçon', '2000-01-01', 0, NULL, NULL, 'QUARTIER DES HOPITAUX RES EL HASSOUNIA  CASABLANCA', NULL, 'Normal', NULL),
('ZINE AMIRA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZINE EL ABIDINE  JANNAT', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BOUSKOURA ---- CASABLANCA', NULL, 'Normal', NULL),
('ZINE EL ABIDINE  WISSAL', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BOUSKOURA ---- CASABLANCA', NULL, 'Normal', NULL),
('ZINE EL ABIDINE ISLAM', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BOUSKOURA ---- CASABLANCA', NULL, 'Normal', NULL),
('ZINE EL ABIDINE ZIAD', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bouskoura - BOUSKOURA', NULL, 'Normal', NULL),
('ZINE FILALI RALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Lotissement mandarona, n°27  CASABLANCA', NULL, 'Normal', NULL),
('ZINE JASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZINE RITA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZINE SARA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZINE YARA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZINEDDINE SAAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '16 RUE ABOU ROUSOUS ETAGE 1 APT 4 ANGLE RUE LA CIGONE
ferme bretonne  CASABLANCA', NULL, 'Normal', NULL),
('ZINIA LAYTH', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RUE NARJISS RES ESPACE DES ARTS IMM C ETG 4 N 22  CASABLANCA', NULL, 'Normal', NULL),
('ZINOUNE YASSINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BEAUSEJOUR   CASABLANCA', NULL, 'Normal', NULL),
('ZIZAH EL GHALIA SARAH', 'Garçon', '2000-01-01', 0, NULL, NULL, '45 BD BIR ANZARANE. RES YOUSSOUFIA MMARIF  CASABLANCA', NULL, 'Normal', NULL),
('ZIZAH RANIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '45 BD BIR ANZARANE. RES YOUSSOUFIA MMARIF', NULL, 'Normal', NULL),
('ZIZI  YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '5AV DES PLEIADES APT 14 RES 3 EL IMRANE  2000 CASABLANCA', NULL, 'Normal', NULL),
('ZKAILI GHITA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RES KARMA 1? RUE MARISCAL AIN B ORJA  CASABLANCA', NULL, 'Normal', NULL),
('ZKAILI YAHYA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RES KARMAA , RUE MARISCAL AIN BORJA  CASABLANCA', NULL, 'Normal', NULL),
('ZMIRLI YAQOUT', 'Garçon', '2000-01-01', 0, NULL, NULL, '79, lot mandar jamil sidi maarouf - CASABLANCA', NULL, 'Normal', NULL),
('ZNAIDI RAYYAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '22 RUE PALMYRE APPARTEMENT 12 -BOURGOGNE - BERKAN', NULL, 'Normal', NULL),
('ZNAIDI ZINEB', 'Garçon', '2000-01-01', 0, NULL, NULL, '22 RUE PALMYRE APPARTEMENT 12-BOURGOGNE  CASABLANCA', NULL, 'Normal', NULL),
('ZNASSNI AHMED-REDA', 'Garçon', '2000-01-01', 0, NULL, NULL, '16, allee lermitage 20000 CASABLANCA', NULL, 'Normal', NULL),
('ZNATI AMIR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Boulevard d''Anfa, rue Ahmed Charci, champs d''Anfa C, 2ème étage, appt 3  CASABLANCA', NULL, 'Normal', NULL),
('ZNATI RAYANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Boulevard d''anfa, rue Ahmad CHARCI, champs d''anfa C, 2ème étage, appt 3  CASABLANCA', NULL, 'Normal', NULL),
('ZNATNI  LYLIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rue ex bazas nabigha doubiani bd ibntachfin  20250', NULL, 'Normal', NULL),
('ZNIBER MEHDI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZNIBER NIZAR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Appt 14 imm a res dream californie. ain chock   CASABLANCA', NULL, 'Normal', NULL),
('ZNIBER YANIS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZOGGARH ANAS', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZOGGARH SOUHAILA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'N°312, Boulevard Abdelmoumen  CASABLANCA', NULL, 'Normal', NULL),
('ZOUAK NACER', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZOUANAT AMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '60, boulevard abdellatif ben kaddour  CASABLANCA', NULL, 'Normal', NULL),
('ZOUARI MEHDI', 'Garçon', '2000-01-01', 0, NULL, NULL, '', NULL, 'Normal', NULL),
('ZOUARI SALMA', 'Garçon', '2000-01-01', 0, NULL, NULL, '37 lot  bouskoura  - BOUSKOURA', NULL, 'Normal', NULL),
('ZOUGGAR ABDERRAHMANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Marrakech - RABAT', NULL, 'Normal', NULL),
('ZOUHAIR AHMED RAYANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Immeuble 110, appt 15, résidence Salam  CASABLANCA', NULL, 'Normal', NULL),
('ZOUHAIR ILYAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
('ZOUHAIR JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, 'AVENUE OUKBA BNOU NAFIA RCE AL HANAA IMM A 20500 CASABLANCA', NULL, 'Normal', NULL),
('ZOUHAIR RITAJE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Immeuble 110, appt 15, résidence Salam  CASABLANCA', NULL, 'Normal', NULL),
('ZOUHAIR SAFWANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CALIFORNIE
 - CASABLANCA', NULL, 'Normal', NULL),
('ZOUHAYR  MOHAMMAD', 'Garçon', '2000-01-01', 0, NULL, NULL, 'CASABLANCA', NULL, 'Normal', NULL),
('ZOUHAYR ROKAYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '61 BD DE BORDEAUX, RESIDENCE TAHA, etg 5 appt10', NULL, 'Normal', NULL),
('ZOUHIR AKSIM', 'Garçon', '2000-01-01', 0, NULL, NULL, '15, rue des Cigales  CASABLANCA', NULL, 'Normal', NULL),
('ZOUHIR NOHAM', 'Garçon', '2000-01-01', 0, NULL, NULL, '39 RUE DU PALMIERS OASIS 20410 CASABLANCA', NULL, 'Normal', NULL),
('ZOULOUTI IMANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bd emile zola apt a 10 res tayba 4 belvedere   CASABLANCA', NULL, 'Normal', NULL),
('ZOULOUTI MED AMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bd emile zola apt a 10 res tayba 4 belvedere   CASABLANCA', NULL, 'Normal', NULL),
('ZRAIDI KHADIJA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'POLO  CASABLANCA', NULL, 'Normal', NULL),
('ZRIDA INES', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Polo casa - CASABLANCA', NULL, 'Normal', NULL),
('ZRIDA YASMINE RIHANA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Al andalos 4  polo casa - CASABLANCA', NULL, 'Normal', NULL),
('ZTOB ALAE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - BOUSKOURA', NULL, 'Normal', NULL),
('ZTOB YOUSSEF', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bouskoura - BOUSKOURA', NULL, 'Normal', NULL),
('ZUGARI CAMELLIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Portes californie, rés du lac, imm 8, apprt 5, ain chok  CASABLANCA', NULL, 'Normal', NULL),
('ZYATE GHAITH', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL);

-- ============================================================
-- FILE 5 DONE! ✅
-- ============================================================
