-- ============================================================
-- TOUPTI GYM CASA - DATA IMPORT - FILE 2 OF 8
-- HORAIRES (exercises table - name = groupe, group_id = activité)
-- ============================================================

-- Run this AFTER FILE 1
-- ============================================================

INSERT INTO exercises (name, day, type, start_time, end_time, coach_id, group_id) VALUES
  ('TOUP''TI POUSS/MOUSS', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('TOUP''TI POUSS/MOUSS', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITS FILOUS', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('MALINS', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('GRANDS MALINS', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRENOUILLES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('TÊTARDS', 'Thursday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('SUPER TÊTARDS', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUSSEF KENZEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('SUPER TÊTARDS', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('BALEINES', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CANARDS', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('BALEINES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CYCLE DE NATATION', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'SOUFIANE EL HADDAD' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('KOALAS', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS', 'Saturday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES', 'Friday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES', 'Saturday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS', 'Saturday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('P''TITES CANAILLES', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('LIONS', 'Friday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('LIONS', 'Wednesday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('LIONS', 'Wednesday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('LIONS', 'Saturday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('KANGOUROUS', 'Friday', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('GUÊPARDS', 'Wednesday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('GUÊPARDS', 'Saturday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('P''TITS FILOUS', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('KANGOUROUS', 'Saturday', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('BALEINES', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GUÊPARDS', 'Friday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('GRENOUILLES', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRANDS MALINS', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('BALEINES', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('REQUINS', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('BALEINES', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Friday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('REQUINS', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'AZIZ TOUMI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('P''TITES CANAILLES', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('BALEINES', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('TÊTARDS', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS SENIOR', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('P''TITES CANAILLES', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('GRANDS MALINS', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('KANGOUROUS', 'Wednesday', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('KANGOUROUS', 'Saturday', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'KAMAL SLAOUI' LIMIT 1), (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('GRENOUILLES', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('MALINS', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('COCCINELLES', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('TAUREAUX', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('GRANDS MALINS', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('DRAGONS', 'Friday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('P''TITES CANAILLES', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('CORADIONS SENIOR', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'SOUFIANE EL HADDAD' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRANDS MALINS', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('MALINS', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('GRANDS MALINS', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES CANAILLES', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Tuesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Monday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('OURS', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('GRENOUILLES', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('TIGRES', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TAUREAUX', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('OURS', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('KOALAS', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('OURS', 'Saturday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('TAUREAUX', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('TAUREAUX', 'Saturday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('GRENOUILLES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS SENIOR', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('STAFF', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('STAFF', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAFF' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('TIGRES', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('LIONS', 'Thursday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('GUÊPARDS', 'Thursday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('COCCINELLES', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('COCCINELLES', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('PAPILLONS', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('DRAGONS', 'Wednesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV INDIVIDUEL', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('RDV EN BINÔME', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BABY SPA' LIMIT 1)),
  ('COCCINELLES', 'Friday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('PAPILLONS', 'Friday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'IRYNA MUZYKA' LIMIT 1), (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('CANARDS', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRENOUILLES', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('GRANDS MALINS', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELMALEK CHAKIR' LIMIT 1), (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('REQUINS', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CYCLE DE NATATION', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CORADIONS SENIOR', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CYCLE DE NATATION', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CANARDS', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('KANGOUROUS', 'Thursday', 'Basketball', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('KOALAS', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TAUREAUX', 'Sunday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('GRANDS MALINS', 'Wednesday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('TOUP''TI POUSS/MOUSS', 'Thursday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('MALINS', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Friday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('P''TITES CANAILLES', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 1' LIMIT 1)),
  ('OURS', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Saturday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('VOLTIGEURS DÉBUTANT', 'Sunday', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE 2' LIMIT 1)),
  ('KOALAS', 'Friday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ABDELHAMID SAADEDDINE' LIMIT 1), (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('OURS', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('TAUREAUX', 'Tuesday', 'Other', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'RIDA MOURAK' LIMIT 1), (SELECT id FROM groups WHERE name = 'KICK-BOXING' LIMIT 1)),
  ('TIGRES', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('CYCLE DE NATATION', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('REQUINS', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Sunday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Saturday', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS BOULGANA' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('PAPILLONS', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('PISCINE 1', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Tuesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Thursday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Friday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 1', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('PISCINE 2', 'Sunday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ABSENCES' LIMIT 1)),
  ('7 - 14 ANS', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'SELF-DEFENSE' LIMIT 1)),
  ('7 - 14 ANS', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'SELF-DEFENSE' LIMIT 1)),
  ('7 - 14 ANS', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'SELF-DEFENSE' LIMIT 1)),
  ('TÊTARDS', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('CANARDS', 'Saturday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION' LIMIT 1)),
  ('LIONS', 'Tuesday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('GUÊPARDS', 'Tuesday', 'Football', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'YOUNES EL HASSANI' LIMIT 1), (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('DAUPHINS', 'Sunday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('KOALAS', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS', 'Monday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('GUÊPARDS', 'Wednesday', 'Football', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('KANGOUROUS', 'Tuesday', 'Basketball', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('KOALAS', 'Saturday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES', 'Wednesday', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('3-6 ANS', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('7-14 ANS', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('3-6 ANS', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('7-14 ANS', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('3-6 ANS', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('7-14 ANS', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('3-6 ANS', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('7-14 ANS', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('7-14 ANS', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE NATATION P2' LIMIT 1)),
  ('3-6 ANS', 'Monday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Tuesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Wednesday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Thursday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1)),
  ('3-6 ANS', 'Friday', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'STAGE DE NATATION P1' LIMIT 1));

-- ============================================================
-- FILE 2 DONE! ✅
-- ============================================================
