-- ============================================================
-- TOUPTI GYM DARBOUAZZA - DATA IMPORT - FILE 1 OF 8
-- ACTIVITÉS (groups) + TRAINERS + HORAIRES (exercises)
-- ============================================================

-- Run this FIRST in the Supabase SQL Editor
-- ============================================================

INSERT INTO groups (name) VALUES
  ('NATATION 1'),
  ('NATATION 2'),
  ('ARTS MARTIAUX'),
  ('GYMNASTIQUE'),
  ('KICK-BOXING'),
  ('KARATE'),
  ('FOOTBALL'),
  ('DANSE CLASSIQUE'),
  ('BASKETBALL');

INSERT INTO trainers (name) VALUES
  ('ANAS NAJI');

INSERT INTO exercises (name, day, type, start_time, end_time, coach_id, group_id) VALUES
  ('GRENOUILLES DÉBUTANTS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS NAJI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('CANARDS DÉBROUILLÉS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS NAJI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Lundi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS NAJI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CYCLE DE NATATION', 'Lundi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS NAJI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', (SELECT id FROM trainers WHERE name = 'ANAS NAJI' LIMIT 1), (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('BALEINES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('DAUPHINS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CANARDS DÉBROUILLÉS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('TÊTARDS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('BALEINES', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('BALEINES', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CANARDS DÉBROUILLÉS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('SUPER TÊTARDS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('DAUPHINS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('TÊTARDS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('SUPER TÊTARDS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('BALEINES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS JUNIOR', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('CANARDS DÉBROUILLÉS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('SUPER TÊTARDS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('TÊTARDS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('P''TITS FILOUS', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('MALINS', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITS FILOUS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('MALINS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('GRANDS MALINS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITS FILOUS', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('MALINS', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('GRANDS MALINS', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITS FILOUS', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('MALINS', 'Vendredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITS FILOUS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('GRANDS MALINS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITS FILOUS', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('MALINS', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITES FRIPOUILLES', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('TOUP''TI POUSS/MOUSS', 'Dimanche', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('KOALAS (3-5 ANS)', 'Mardi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES (6-8 ANS)', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS (3-5 ANS)', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES (6-8 ANS)', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS (3-5 ANS)', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS (3-5 ANS)', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES (6-8 ANS)', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS (9-14 ANS)', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES (6-8 ANS)', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES (6-8 ANS)', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS (3-5 ANS)', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES (6-8 ANS)', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES (6-8 ANS)', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('TIGRES (6-8 ANS)', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('6-15 ANS', 'Jeudi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'KARATE' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('DRAGONS (9-14 ANS)', 'Vendredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS (9-14 ANS)', 'Dimanche', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('KOALAS (3-5 ANS)', 'Lundi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('DRAGONS (9-14 ANS)', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRANDS MALINS', 'Lundi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('CANARDS DÉBROUILLÉS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('MALINS', 'Mercredi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('LIONS', 'Mercredi', 'Football', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('GUÊPARDS', 'Mercredi', 'Football', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('KANGOUROUS', 'Mercredi', 'Basketball', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('COCCINELLES', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('PAPILLONS', 'Mercredi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('GRANDS MALINS', 'Jeudi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('CANARDS DÉBROUILLÉS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CORADIONS SENIOR', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CYCLE DE NATATION', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CANARDS DÉBROUILLÉS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('MALINS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('GRANDS MALINS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITS FILOUS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('P''TITS FILOUS', 'Samedi', 'Gymnastics', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'GYMNASTIQUE' LIMIT 1)),
  ('COCCINELLES', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('PAPILLONS', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'DANSE CLASSIQUE' LIMIT 1)),
  ('LIONS', 'Samedi', 'Football', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('GUÊPARDS', 'Samedi', 'Football', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'FOOTBALL' LIMIT 1)),
  ('KANGOUROUS', 'Samedi', 'Basketball', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'BASKETBALL' LIMIT 1)),
  ('KOALAS (3-5 ANS)', 'Samedi', 'Other', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'ARTS MARTIAUX' LIMIT 1)),
  ('BALEINES', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('BALEINES', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('REQUINS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CANARDS DÉBROUILLÉS', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Mercredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CANARDS DÉBROUILLÉS', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CYCLE DE NATATION', 'Jeudi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('BALEINES', 'Vendredi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('CANARDS DÉBROUILLÉS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('BALEINES', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 2' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Lundi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Dimanche', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1)),
  ('GRENOUILLES DÉBUTANTS', 'Samedi', 'Swimming', '09:00:00', '10:00:00', NULL, (SELECT id FROM groups WHERE name = 'NATATION 1' LIMIT 1));

-- ============================================================
-- FILE 1 DONE! ✅ Run FILE 2 next.
-- ============================================================
