-- ============================================================
-- TOUPTI GYM DARBOUAZZA - DATA IMPORT - FILE 2 OF 8
-- CHILDREN
-- ============================================================

-- Run this AFTER FILE 1
-- ============================================================

INSERT INTO children (name, gender, birth_date, age, school, school_type, address, postal_code, client_type, zkteco_id) VALUES
  ('ABBAT GHASSAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
  ('ABDELMOTALEB CHAHD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ABDELMOUTTALIB JULIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ABDERRAHIM ZIAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ABDUDDAHAB EVA LYNA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ABIDI RAGHAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
  ('ABLI MED GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ABOUAM  CHAHD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ABOUCHRA LYNE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Dar bouazza - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ADNANE YANIS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ADNANE YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AFFANE SHEMS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AFSAHI ISMAIL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AGOUMI GHALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AHAYARE YACOUT', 'Garçon', '2000-01-01', 0, NULL, NULL, '113 RES EL MOHIT - CASABLANCA', NULL, 'Normal', NULL),
  ('AIT SEDDIK GHASSANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AIT SEDDIK GHITA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AL ACHBILI MED KARIM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AL ACHBILI SHAMS EDDINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AL SABIAI JOURI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Bab salam - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALAMI ARIJ', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Residence Panoramique, Villa 6  DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALAMI KENZA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALAMI MOHAMED ILYAS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALAOUI ADAM', 'Garçon', '2000-01-01', 0, NULL, NULL, 'DOMAINE DE DARB-Dar Bouazza - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALAOUI LAMDAGHRI JUDE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Ain Diab - CASABLANCA', NULL, 'Normal', NULL),
  ('ALAOUI LAMDAGHRI LARA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Ain Diab - CASABLANCA', NULL, 'Normal', NULL),
  ('ALAOUI MHAMDI YAZID', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Residence seaside luxury living  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALAOUI NAEL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALAWWAD SULTAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALBI ILIEN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALDABDOUB JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALDABDOUB JOUDIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALMEER ABDOULLA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'QATAR - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ALSAFI RAKAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AMAMA TALIA YAKOUT', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ANSSETI YULIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AOUED ALYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ASMLAL YOURI SULTAN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rés diams tamariss  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ASSAL GARNIGA  VALENTINA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Beach Front Villa, Villa 92, Dar Bouazza  DAR BOUAZZA', NULL, 'Normal', NULL),
  ('AZELARAB YOUSSEF', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BAADI GHALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BAALI ALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Océan frend 3 ----- CASABLANCA', NULL, 'Normal', NULL),
  ('BACHAR YARA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BADAOUI  ALYA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Residence les jardins de tamaris  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BAHAJI ZYAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BAITE MERYEM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BAKKALI ALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BAKKALI MOHAMED HACHIM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BALBAL YAKOUTE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BARAKAT OTHMAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BAREHMI MAYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BARROIS ALYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BEGDOURII ISMAIL', 'Garçon', '2000-01-01', 0, NULL, NULL, '* - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BEJAOUI JEBARI HOUD', 'Garçon', '2000-01-01', 0, NULL, NULL, 'N 53 LOT ANSURY  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BEKHALI LILYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BELABID AMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BELLAHIM AYLINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'LES VILLAS DANFA 2 LOT 79 DAR BOUAZZA  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BELLAKHDAR LILYA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res diar amine inn16 etg 3 apt 17  CASABLANCA', NULL, 'Normal', NULL),
  ('BEN AYOUB DIANA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Residence aigue marine imm g appart 1 dar bouazza  --- CASABLANCA', NULL, 'Normal', NULL),
  ('BEN HADDOUCH MARYEM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BEN MATLOUK JOURY', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENABDELLAH LILIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENBRAHIM AMINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '----- ----- CASABLANCA', NULL, 'Normal', NULL),
  ('BENBRAHIM ISMAIL', 'Garçon', '2000-01-01', 0, NULL, NULL, '----- ----- CASABLANCA', NULL, 'Normal', NULL),
  ('BENBYA ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENCHAHID YOUNES', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Palm océon villa ds 6 - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENHAYOUN LINA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BRISE MARINE - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENJABBOUR MOHAMED IYAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENJEBARA LARA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENJEBARA LAYANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENJELLOUN ALYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENJELLOUN BAHIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENJELLOUN LYNE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENJELLOUN SIDI MOHAMED', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENJELLOUN YAKOUT', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENNANI NAEL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENNANI SMIRES LARA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENNANI ZINEB', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENNIS YACOUT', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENSALAH ALIYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- * DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENSALAH SHAMA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENSERAKH MED AMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'DAR BOUAZZA CASA - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENSERRAKH JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENYAHYA  YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res océan - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BENZIDANE YOUSSEF', 'Garçon', '2000-01-01', 0, NULL, NULL, '56 villas d"anfa 3 - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BERRADA LILYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BERRADA MYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOLGOT JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BORGA HIBA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res azur - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BORGAA GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res azur  - CASABLANCA', NULL, 'Normal', NULL),
  ('BORGAA RITA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
  ('BOUAAMRI FARES', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOUADDI MED ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Les oalm garden - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOUCHAREB APOLLO', 'Garçon', '2000-01-01', 0, NULL, NULL, 'DAR EL KENZ - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOUDLAL SOPHIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOUHCINE GHALYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOUIH GHALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOUNJOUL LINA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Residnce Seaside - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOURAOUI YASSINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOURAS MEYA JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOUREZG HANAA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Résidence balea n21 ---- CASABLANCA', NULL, 'Normal', NULL),
  ('BOUREZG RITAJ', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Residence balle an ----- TEMARA', NULL, 'Normal', NULL),
  ('BOURI YAHYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('BOUTARBOUCH IMRANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CANO CHAFIQ NOAH', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHACHOUA JASSIM', 'Garçon', '2000-01-01', 0, NULL, NULL, '12LOT LAMIARESSAFA ---- CASABLANCA', NULL, 'Normal', NULL),
  ('CHAFAI ANAS', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Ain sebaa - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHAFAI SAMI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Ain sebaa - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHAFAI SAMIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHAFIQ RAKAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHAGDOUNE NOUR', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHAHBOUNI ZIYAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHAMI JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHAMI MED GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHARKAOUI KENZA  AL BATOUL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
  ('CHAUVIN ENZO', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHAUVIN JULES', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHAYBAN ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rés la vallé dar bouazza  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHBANI KENZA LYN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHEIKH SARAH', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHERFI HABIBA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'APPART 4 IMMEUB 4 RESIDENCE SEASIDE  ---- CASABLANCA', NULL, 'Normal', NULL),
  ('CHERKAOUI ALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHERMATI IMRANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHERMATI YAACOUB', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHIBANE ELI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'BLUELOTOS VILLA 45
 - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('CHRAIBI JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('DAHBI KENZA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('DAIF NADINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'EL FAL TAMARIS IMM 01 - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('DALOUADI SOPHIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Domaines de darb immeuble f apt 24 darb --- CASABLANCA', NULL, 'Normal', NULL),
  ('DAMIRI ILAF', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Domaine de Darb , villa 75 - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('DARII ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('DASSOULI AYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('DASSOULI MALAK', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('DECAMPS COLETTE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('DECAMPS LOUP', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Dar bouazza jardin de l''océan  ----- CASABLANCA', NULL, 'Normal', NULL),
  ('DIOURI  AYLA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Résidence beachjrant villa 131 ---- CASABLANCA', NULL, 'Normal', NULL),
  ('DOULIAZAL AHMED CHOUAIB', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('DOULIAZAL MAHMOUD ALY', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EBINA AMIR', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EBINA JANA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EJ-JADI YACOUTE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL ABDI RANIM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL AKKATI DAHLIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL ALAOUI RITA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL AMTARI SHEMSY', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL ANBI GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL AYOUBI AYDEN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL BAHI YAACOUB', 'Garçon', '2000-01-01', 0, NULL, NULL, '118 LOT RIAD SOFIA  - CASABLANCA', NULL, 'Normal', NULL),
  ('EL BAHRI KHALIL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL BAHRI NOUHA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL BASITY SOPHIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL BOUTE GHITA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL FADILI MOHAMED MAMOUNE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL FILALI NAYLA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL GHAMIRI AIDA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL GOURRAMI  ZIAD', 'Garçon', '2000-01-01', 0, NULL, NULL, 'MDINAT ERRAHMA RESIDENCE EL KEIR CASA 20230 DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL GUEDDOUDI YASMINA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'ATLANTIC EDEN - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL HACHIMI ALAMI MOHAMED', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL HAJRAOUI NOUHANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL HAJRAOUI RADIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'VILLAGE PILOTE  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL HARTI GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL HASSANI CHADYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL JABRI GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Villa des prés - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL KADIOUI EL IDRISSI JOUDIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'SIDI REHAL CHATII ------ CASABLANCA', NULL, 'Normal', NULL),
  ('EL KALAMI JUDY', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL KANDOUSSI ASSYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL MACEN LWIZA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL MACEN MAY', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL MADI LINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL MAKAOUI SOFIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL MAKAOUI YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL MGANI MAYLINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'PALM OCEON  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL MGANI YANIS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL MOUTII YAZAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL MRINI HIBA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL OMARI MOHAMED', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL OUARMA HAROUN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL OUROUBA CAMELIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL OUROUBA RYM', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RES OCEAN PALM VILLA 190 - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL TAWOS GHITA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL WAHMANI AYLAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL YOUSSI INÉS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL YOUSSOUFI MED YASSINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EL YOUSSOUFI SAMY', 'Garçon', '2000-01-01', 0, NULL, NULL, '36 lotissement  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ELMARS SOFIA LENA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ELOITRI JOUDIYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ELOITRI YANIS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ENNAJI LYLA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
  ('ENNAZIH HIBA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ENNAZIH ISRAA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ESSADIK RITA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res sancy quartier Almaz - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ETTALBI MAMOUNE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ETTARGHY IMRANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('EVIN ILYANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('FADOUNI MED AMIR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Diar chatii gh19 imm4 2eme etage N3  DAR BOUAZZA', NULL, 'Normal', NULL),
  ('FAHIM EL IDRISSI YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('FAHL SOFIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RESIDECE PENINSULA - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('FAKHIR REEM', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rés aboud oulfa bd molay thami casa --- CASABLANCA', NULL, 'Normal', NULL),
  ('FALAH AHMED', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('FALLET ILYANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('FATHALLAH SAMI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('FELLAH AYA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Lot 34 abrar  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('FIBAR ADAM', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Résidece squre imm 2appart9 darb ---- CASABLANCA', NULL, 'Normal', NULL),
  ('FIBAR JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('FIRSOVA POLINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GARCIA LAZRAK NOAM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GHALLAB AYLAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GHANEM HIBA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GHARBI ELIAS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GHARSALLI LYNA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GORRAM AMIR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res janat tamaris imm 05  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GOURRA MIKHAIL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GOURRA SAYALINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GUEMMI AMIR', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GUEMMI ANIS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GUENNONUNI ALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('GUILLABERT LILIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HADDAD ALAA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HAJJAMI LYDIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'DAR EL KENZ  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HALIMI GHITA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rés les collines - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HALIMI MEHDI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HALLAL YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HAMDAOUI JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HAMIDA INES', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RESIDENCE ANFA HEAVEN - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HASSARI AMIRA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HATHOUT YAHYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HATROUHOU ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Aigue harine residence ----- CASABLANCA', NULL, 'Normal', NULL),
  ('HILAL GHITA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HILAL KAMELIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HIMI INES', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('HOUSNI YOUSSEF', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('IDRISSI SERGHINI CYLIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'DOMAINE DE DARB - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('IHATCHANE AWAB', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('IHATCHANE MONIB', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('IMARA SOPHIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('JABIRI MANAL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('JABIRI MOHAMED ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Ocean bay  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('JAMI NELYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('JAMIL HAROUN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Lot tamaris anfa  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('JAMIL SOULAIMAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('JARRAR GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KABBAJ AYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KAFI HAJAR', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KALHI IMRANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KAMMOURI ALAMI RIAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KARAM GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'JANAT TAMARIS - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KARIM IZZA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KHAMMAL MED JADE', 'Garçon', '2000-01-01', 0, NULL, NULL, '* - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KHAOULANI HANAE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KHARDISSE KAMIL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KHARDISSE YANIS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KHARYF ABDERRAHMANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KHELIFI YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('KOUBACH ILAF', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
  ('L MOUTAWAKIL IMRANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAADEL JOUDIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAALAHMI YASSER', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAANAYA NOAH', 'Garçon', '2000-01-01', 0, NULL, NULL, 'DAR BOUAZZA ------ CASABLANCA', NULL, 'Normal', NULL),
  ('LAATMANI AZAR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Route azman
route azemour bab alrayan b6 darbouazza - CASABLANCA', NULL, 'Normal', NULL),
  ('LABAID LARA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res soleil imm 07  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LABIAD RIAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LABRAIMI NACER', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAHFID MEHDI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAHFID SARA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAHLALI LILYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAHLOU ADAM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAHLOU DINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAHLOU SARAH', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAMCHARRAF MIYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAMRANI JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAMSADDEK YANISS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAMZAWAK MEILYNE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAMZAWAK ROMAISSAA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAOUNI IBRAHIM', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Dar el kenz - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAOUNI KHADIJA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAOUNI YOUCEF', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LARAKI SELYANN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'VILLAS PRES  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAYACHI ILYANA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAZRAK CAMELIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAZRAK CAMÉLIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LAZRAK GHALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LE BOUIL CHARLOTTE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LE BOUIL MATHIS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- +- DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LEBBADI GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LEBBAR AMIR', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LEBBAR MALAK', 'Garçon', '2000-01-01', 0, NULL, NULL, '-
- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LEMKIESSI JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LEZHARI RANYA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Q.almaz ambar 3 A3 - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LIAS NORA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LIAS YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LMARBOUH AYLAN', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Beach front villa N 172 - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LOTFI MARIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Dar Bouazza - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('LOUDGHIRI AIDA', 'Garçon', '2000-01-01', 0, NULL, NULL, '----- ----- CASABLANCA', NULL, 'Normal', NULL),
  ('LOUDGHIRI DRISS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - CASABLANCA', NULL, 'Normal', NULL),
  ('MAAD CAMIL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MACHRAH WALID', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MADDALUNO ELLA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Résid o pale square imm 33 aprt2darb 27223 CASABLANCA', NULL, 'Normal', NULL),
  ('MANSOUR ISMAEL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MANSOUR MARIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MANSOURI  IDRISSI SARAH', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MANSOURI IDRISSI NOUR', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MAZOUZ  AIDA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Seaside imm 2appt16dar bouazza  --- CASABLANCA', NULL, 'Normal', NULL),
  ('MEFTOUL RADIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MELHAOUI YAKOUT', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MELLAKH MAY', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MESFIOUI ILYAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MESFIOUI MAYLINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MESRAR SAMY', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Palm garden -- DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MIRANI ZAYNE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MIRIAL SHADI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MLAHFI GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOKHAYAR YURI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOKSSIT MALAK', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUHSINE MED ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUHSINE MED GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUINE MOHAMED ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUKAFIH INES', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOULINE MAYA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Km 10routed''azemour res vert marine ----- CASABLANCA', NULL, 'Normal', NULL),
  ('MOUNTASSER YAKOUT ILYANA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUQTASSID DINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUQTASSID IYAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUSSAID SALMA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUSSAOUI ISMAIL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUSTAJAB DOAA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUSTAJAB TAHA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('MOUTAKKI LINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NACEUR SARA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NADER TILILA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NADER TITTRIT', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NADIFI AHMED GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NADIR LYNE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NADIR YASSMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NADLOUSSE JAD EL GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Fadaat al mouhit, GH20, IMM37  DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NAGGAY CHAHD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NAGGAY FIRAS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NAGGY SIRAJ', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NAIMI LEYLA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NAIMI SARAH', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NASSIB MIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NASSIR HEDI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NEHILI ALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NEHILI GHITA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NOKRACHI LILYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NOUSSAIRI LIAM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('NUNEZ VENTOSA MAILA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('OTARID YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('OUALI  ALAMI ACHRAF', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('OUDGHIRI KENZA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('OUEDAIE MOHAMED', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('OUEDAIE SHEHRAZAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('OUFARES INES', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('OUGZOULY SARA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('OUISSAFANE LYNE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'N°82 LOT PAVILLON OUED MERZEG  CASABLANCA', NULL, 'Normal', NULL),
  ('OUSSALLAMI  SIRAJ', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('OUSSALLAMI RODAYNA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('OZAID SALMANE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'SUN SQUARE ALMAZ QYARTIER ALMAZ - CASABLANCA', NULL, 'Normal', NULL),
  ('PERAIN LAYLA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('PISKORSKI NELLE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RACHID MOHAMED GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RADI SOULAYMANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '---- ---- CASABLANCA', NULL, 'Normal', NULL),
  ('RAGHMOUNE RYM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RAHMAN MAISSA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RAHMAN MALIK', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RAHMOUNI EL IDRISSI EYLINE', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Next house villa 6 - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RAMID JAD', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RANIA KASMI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RASSID ZIYAD', 'Garçon', '2000-01-01', 0, NULL, NULL, 'LOT AL MOHITE IMM 189  appt 06 - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('REDOUAN KENZA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('REGRAGUI ADAM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('REGRAGUI NIZAR', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RGHIOUI NELYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '118 OCEAN PLAN  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RHAZLAOUI NOUR', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('RIMAL JANNAT', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ROCHDI RITA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ROUIYESS DALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SAADALI LEYNA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Beachfront villas 152 darbouaza ----- CASABLANCA', NULL, 'Normal', NULL),
  ('SAADI RIM', 'Garçon', '2000-01-01', 0, NULL, NULL, '21 ld amoou,sidi rahhal - CASABLANCA', NULL, 'Normal', NULL),
  ('SABRI HARON', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res golden  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SAHAKI LILIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SAID-EDDINE IDRIS', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Res al boustane + DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SAKHI ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'El alia gh 4 imm 20 - CASABLANCA', NULL, 'Normal', NULL),
  ('SALEM GHALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SALHI DINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SALHI NADINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SALIH GHALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SAMPERIZ JULIETTE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SARIH SAMI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SENHAJI CAMELIA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Beach front  - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SGHIRY LILYA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Rue ahmedkadmi


rue ahmed kadmiri résidence loraseseliers b étage 5 ap25 ---- CASABLANCA', NULL, 'Normal', NULL),
  ('SIDQUI ISRAE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SMIRES MARIAH', 'Garçon', '2000-01-01', 0, NULL, NULL, 'RESIDENCE SHAHRAZAD-VILLA N100-DAR BOUAZZA - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SNADROU JANA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Jnan al mohit gh2imm16apt16darbouazza ----- DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SOULEIMANI KENZA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Dar bouaza - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('SRERHO ALYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('STUDER SOHAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TADLAOUI ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TADLAOUI ALIAE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TAGHI KENZA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TAMMOR YASMINE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TAOUJNI CAMELIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TAZI  SHEMSY', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TIROCH AYALA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TLEMCANI INES', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TOFAILI KAMIL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TOUINSSI AMIR ILYANE', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('TOUZANI RHALIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('WAKRIM ALI', 'Garçon', '2000-01-01', 0, NULL, NULL, 'MANZEH SAHEL HAD SOUALEM - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('WARI LILIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('WERZGAN LILYA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('WZEZGAN HAROUN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('YAACOUBI HOUSSA  AMIR', 'Garçon', '2000-01-01', 0, NULL, NULL, 'Oulfa résidence perles de oulfa  ---- CASABLANCA', NULL, 'Normal', NULL),
  ('YASSINE MAHA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('YOURI NELYS', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZAABLI LINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZAHRIBE DINA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZALEGH NAOUFEL', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZEROUAL LEYNA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZHAO YAMAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZINOUN JOUDIA', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZNIBER RITA', 'Garçon', '2000-01-01', 0, NULL, NULL, 'VILLAS DES PRés - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZORAA AWAB', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZOUGGARI MARYAM', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZOUGGARI SALEYMAN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZOUHAIR MALAK', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL),
  ('ZRIKEN ZAYN', 'Garçon', '2000-01-01', 0, NULL, NULL, '- - DAR BOUAZZA', NULL, 'Normal', NULL);

-- ============================================================
-- FILE 2 DONE! ✅
-- ============================================================
